FROM ubuntu:24.04

ARG SERVER_IP_ADDR

ENV DEBIAN_FRONTEND=noninteractive

RUN apt -y update
RUN apt -y -f install
RUN apt -y install openvpn easy-rsa iproute2 dnsmasq

# Configuring Certificate Authority (Steps 1 && 2)
RUN mkdir /easy-rsa
RUN ln -s /usr/share/easy-rsa/* /easy-rsa/
COPY config_files/easy_rsa_vars /easy-rsa/vars
RUN cd /easy-rsa; ./easyrsa init-pki; echo -e "\n" | ./easyrsa build-ca nopass

# Configuring server certificate (Steps 3 && 4)
RUN cd /easy-rsa; echo -e "\n" | ./easyrsa gen-req vpn-server nopass
RUN cp /easy-rsa/pki/private/vpn-server.key /etc/openvpn/server/
# RUN cd /easy-rsa; ./easyrsa import-req /easy-rsa/pki/reqs/vpn-server.req vpn-server
RUN cd /easy-rsa; echo "yes" | ./easyrsa sign-req server vpn-server
RUN cp /easy-rsa/pki/issued/vpn-server.crt /etc/openvpn/server/
RUN cp /easy-rsa/pki/ca.crt /etc/openvpn/server/

# OpenVPN cyptography setup (Step 5)

RUN cd /easy-rsa; openvpn --genkey --secret ta.key; cp ta.key /etc/openvpn/server

# Skip client configuration, it is done later in runtime (Step 6)

# Configuring openvpn (Step 7)

COPY config_files/server.conf /etc/openvpn/server/server.conf

# Configuring IP forwarding (Step 8)

RUN echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.conf
RUN sysctl -p

# Brandmauer counfiguration (Step 9)

# TODO, skip for now

# Start OpenVPN (Step 10)

# Skip since server is run inside docker container manually, no systemd is involved

# Prepare infrastructure for client management (Step 11)

RUN mkdir -p /client-configs/files
RUN mkdir -p /client-configs/keys

COPY config_files/client_base.conf /client-configs/client_base.conf
RUN echo -e "\nremote $SERVER_IP_ADDR 443" >> /client-configs/client_base.conf

COPY utils/add_client.sh /utils/add_client.sh
COPY utils/startup.sh /utils/startup.sh
