FROM pytorch/pytorch:2.5.1-cuda12.4-cudnn9-runtime

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update
RUN apt install -y wget git python3 python3-venv libgl1 libglib2.0-0 python3-tk google-perftools bc libcusparse11
RUN git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui /tools/stable-diffusion-webui
RUN git clone --recursive https://github.com/bmaltais/kohya_ss /tools/kohya_ss
RUN git clone https://github.com/binarman/auto-sd-paint-ext /tools/stable-diffusion-webui/extensions/auto-sd-paint-ext
RUN pip3 install flask nvsmi pyte

RUN rm -r /tools/stable-diffusion-webui/models/Stable-diffusion /tools/stable-diffusion-webui/models/VAE
RUN ln -s /models/stable-diffusion /tools/stable-diffusion-webui/models/Stable-diffusion
RUN ln -s /models/lora /tools/stable-diffusion-webui/models/Lora
RUN ln -s /models/vae /tools/stable-diffusion-webui/models/VAE

RUN ln -s /models/stable-diffusion /tools/kohya_ss/models/stable-diffusion
RUN ln -s /dataset/ /tools/kohya_ss/external_dataset

COPY utils/ /tools/
RUN  /tools/startup.sh --prepare-environment

WORKDIR /tools

ENTRYPOINT /tools/startup.sh
