FROM rocm/pytorch

RUN apt update
RUN apt install -y wget git python3 python3-venv libgl1 libglib2.0-0
RUN git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui /stable-diffusion-webui
RUN rm -r /stable-diffusion-webui/models/Stable-diffusion /stable-diffusion-webui/models/VAE
RUN ln -s /models/stable-diffusion /stable-diffusion-webui/models/Stable-diffusion
RUN ln -s /models/lora /stable-diffusion-webui/models/Lora
RUN ln -s /models/vae /stable-diffusion-webui/models/VAE

WORKDIR /stable-diffusion-webui

ENTRYPOINT ./webui.sh -f --listen
