FROM rocm/pytorch

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update
RUN apt install -y wget git python3 python3-venv libgl1 libglib2.0-0 python3-tk google-perftools bc software-properties-common
RUN add-apt-repository ppa:deadsnakes/ppa -y
RUN apt update
RUN apt install python3.12 python3.12-venv
RUN pip3 install flask nvsmi pyte

RUN git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui /tools/stable-diffusion-webui
RUN git clone --recursive https://github.com/bmaltais/kohya_ss /tools/kohya_ss
RUN git clone https://github.com/comfyanonymous/ComfyUI /tools/ComfyUI

RUN rm -r /tools/stable-diffusion-webui/models/Stable-diffusion /tools/stable-diffusion-webui/models/VAE
RUN ln -s /models/stable-diffusion /tools/stable-diffusion-webui/models/Stable-diffusion
RUN ln -s /models/lora /tools/stable-diffusion-webui/models/Lora
RUN ln -s /models/vae /tools/stable-diffusion-webui/models/VAE

RUN ln -s /models/stable-diffusion /tools/kohya_ss/models/stable-diffusion
RUN ln -s /dataset/ /tools/kohya_ss/external_dataset

RUN rm -r /tools/ComfyUI/models/diffusion_models /tools/ComfyUI/models/loras /tools/ComfyUI/models/vae
RUN ln -s /models/stable-diffusion /tools/ComfyUI/models/diffusion_models
RUN ln -s /models/lora /tools/ComfyUI/models/loras
RUN ln -s /models/vae /tools/ComfyUI/models/vae

COPY utils/ /tools/
RUN /tools/startup.sh --prepare-environment

WORKDIR /tools

ENTRYPOINT /tools/startup.sh
