FROM pytorch/pytorch:2.5.1-cuda12.4-cudnn9-runtime

LABEL triton_env="dev"

ARG USER_NAME
ARG USER_EMAIL
ARG INITIAL_TRITON_BRANCH

COPY config_files/bash_env /root/bash_env
COPY config_files/vimrc /root/.vimrc
COPY config_files/bash_aliases /root/.bash_aliases

COPY utils /utils

ENV DEBIAN_FRONTEND=noninteractive

RUN apt -y update
RUN apt -y -f install
RUN apt -y install less strace wget psmisc gdb git clang vim bc
RUN git config --global user.name "$USER_NAME"
RUN git config --global user.email "$USER_EMAIL"
RUN pip3 uninstall -y triton
RUN pip3 install pandas matplotlib pre-commit lit pytest pybind11 ninja pytest-xdist
RUN ln -s /opt/conda/lib/python3.11/site-packages/nvidia/cublas/lib/libcublas.so.12 /opt/conda/lib/libcublas.so

# Initialize bashrc
RUN mv /root/.bashrc /root/bashrc.back; echo "force_color_prompt=yes" | cat - /root/bashrc.back > /root/.bashrc
RUN echo "source ~/bash_env" >> /root/.bashrc

WORKDIR /triton
ENTRYPOINT /utils/prepare_triton_repo.sh -s -b "$INITIAL_TRITON_BRANCH" /triton; bash

