FROM nvidia/cuda:13.0.3-devel-ubuntu24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update
RUN apt install -y curl zstd wget git python3 python3-pip python3-venv libgl1 libglib2.0-0 python3-tk bc libcusparse12 software-properties-common locales cmake
RUN add-apt-repository ppa:deadsnakes/ppa -y
RUN apt update
RUN apt install -y python3.12 python3.12-venv
RUN python3 -m venv /system-venv
RUN . /system-venv/bin/activate; pip3 install flask nvsmi pyte psutil ninja
RUN sed -i -e 's/# ru_RU.UTF-8 UTF-8/ru_RU.UTF-8 UTF-8/' /etc/locale.gen && locale-gen
ENV LANG=ru_RU.UTF-8
ENV LC_ALL=ru_RU.UTF-8

COPY init_utils/ /init_utils
RUN /init_utils/clone_tools.sh
RUN /init_utils/adjust_directories.sh
RUN . /system-venv/bin/activate; /init_utils/build_dependencies.sh
RUN rm -r /init_utils

COPY utils/ /tools/

WORKDIR /tools

ENTRYPOINT . /system-venv/bin/activate; /tools/startup.sh
