#!/usr/bin/bash
echo "UID: $UID"
echo "EUID: $EUID"
echo "cmd: $0"
if test $UID -ne 0; then
  if [[ -z $VPN_PASSWORD ]] || [[ -z $VPN_ADDRESS ]] || [[ -z $VPN_USER ]]; then
    echo "please, set VPN_PASSWORD, VPN_ADDRESS and VPN_USER environment variables"
    exit
  fi
  sudo $0 "$VPN_USER" "$VPN_PASSWORD" "$VPN_ADDRESS"
else
  VPN_USER="$1"
  VPN_PASSWORD="$2"
  VPN_ADDRESS="$3"
  if [[ -z $VPN_PASSWORD ]] || [[ -z $VPN_ADDRESS ]] || [[ -z $VPN_USER ]]; then
    echo "help: connect <VPN_USER> <VPN_PASSWORD> <VPN_ADDRESS>"
    exit
  fi
  echo -e "${VPN_PASSWORD}\n1" | openconnect --protocol=gp "${VPN_ADDRESS}" --user=${VPN_USER} --passwd-on-stdin
fi

