FROM rocm/pytorch

COPY bashrc_addon /root/bashrc_addon
COPY vimrc /root/.vimrc
COPY bash_aliases /root/.bash_aliases

COPY utils /utils

RUN apt -y update
RUN apt -y install less strace wget psmisc
RUN git config --global user.name "Alexander Efimov"
RUN git config --global user.email "efimov.alexander@gmail.com"
RUN pip3 install pandas matplotlib pre-commit lit

# Initialize bashrc
RUN mv /root/.bashrc /root/bashrc.back; echo "force_color_prompt=yes" | cat - /root/bashrc.back /root/bashrc_addon > /root/.bashrc

WORKDIR /triton
ENTRYPOINT /utils/prepare_triton_repo.sh /triton; bash

