FROM rocm/pytorch

COPY bashrc /root/.bashrc
COPY vimrc /root/.vimrc
COPY prepare_triton_repo.sh /prepare_triton_repo.sh

RUN apt update
RUN git config --global user.name "Alexander Efimov"
RUN git config --global user.email "efimov.alexander@gmail.com"
RUN pip3 install pandas matplotlib pre-commit

WORKDIR /triton
ENTRYPOINT /prepare_triton_repo.sh /triton; bash

